version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: servus-postgres-hlg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: servusdb
      POSTGRES_USER: servus
      POSTGRES_PASSWORD: servus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
